//
// Created by Aman on 19-07-2023.
//

#ifndef RUBICSCUBESOLVER_GENERICRUBICSCUBE_H
#define RUBICSCUBESOLVER_GENERICRUBICSCUBE_H


class GenericRubicsCube {

};


#endif //RUBICSCUBESOLVER_GENERICRUBICSCUBE_H
